// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddBoxShadowController from "./add_box_shadow_controller"
application.register("add-box-shadow", AddBoxShadowController)

import BgColorChangeController from "./bg_color_change_controller"
application.register("bg-color-change", BgColorChangeController)

import ContactFormController from "./contact_form_controller"
application.register("contact-form", ContactFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProjectCardHoverController from "./project_card_hover_controller"
application.register("project-card-hover", ProjectCardHoverController)

import ScrollRevealController from "./scroll_reveal_controller"
application.register("scroll-reveal", ScrollRevealController)

import ScrollToSectionController from "./scroll_to_section_controller"
application.register("scroll-to-section", ScrollToSectionController)
