// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BgColorChangeController from "./bg_color_change_controller"
application.register("bg-color-change", BgColorChangeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProjectCardHoverController from "./project_card_hover_controller"
application.register("project-card-hover", ProjectCardHoverController)
